### ISSUE TITLE
Request for an Integrated Deployment File Combining Speakr and onerahmet/openai-whisper-asr-webservice:latest

### ISSUE THREAD

**Issue by simplify123** [murtaza-nasir/speakr#14]
Hello,
I have been trying to deploy Speakr along with the onerahmet/openai-whisper-asr-webservice:latest container, but I encountered some difficulties. The current codebase seems a bit disorganized, and after local testing, I found that it doesn't run as expected.
It would be extremely helpful if you could provide an integrated deployment file that combines Speakr and the openai-whisper-asr-webservice. This would make it easier for users like me to set up the environment without having to manually configure and troubleshoot the integration.
Here are some details about the issues I faced:
The existing code structure is a bit confusing, and there are some dependencies that are not clearly documented.
It would be great if the deployment file could include clear instructions on how to set up the environment, including any necessary environment variables and configurations.
Thank you for your time and effort. I believe this integration would be beneficial for many users who are looking to deploy Speakr with the openai-whisper-asr-webservice.
By the way,i tried this: https://github.com/simplify123/speakr  but localai doesn't support Speaker Diarization and Speaker Identification.

Best regards,
Simplify123

**Comment by murtaza-nasir** [comment]
I am sorry but I don't understand why you're having a problem with the codebase, when you have the option of using a prebuilt docker container. All the instructions are in the readme, I even shared my docker compose for the ASR package. I do not have the time to explain the codebase for you or organize it for you.

I do not use a single docker compose for both speakr and onerahmet/openai-whisper-asr-webservice since I run them on separate machines. But you don't have to do ANYTHING with the codebase to get this to work. 

My onerahmet/openai-whisper-asr-webservice compose file:

``` yml
services:
  whisper-asr-webservice:
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
    container_name: whisper-asr-webservice
    ports:
      - "9000:9000"
    environment:
      - ASR_MODEL=distil-large-v3
      - ASR_COMPUTE_TYPE=int8
      - ASR_ENGINE=whisperx
      - HF_TOKEN=hf_xxx
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["4"]
    restart: unless-stopped
```

My docker-compose for speakr:

``` yml
services:
  app:
    build: .
    image: learnedmachine/speakr:latest
    container_name: speakr
    restart: unless-stopped
    ports:
      - "8899:8899"
    environment:
      - TEXT_MODEL_BASE_URL=https://openrouter.ai/api/v1
      - TEXT_MODEL_API_KEY=sk-or-v1-xxx
      - TEXT_MODEL_NAME=qwen/qwen3-30b-a3b-04-28

      - USE_ASR_ENDPOINT=true  # <--- need this for the ASR endpoint

      - TRANSCRIPTION_BASE_URL=https://api.openai.com/v1 # <- not needed if using ASR
      - TRANSCRIPTION_API_KEY=sk-proj-xxx # <- not needed if using ASR
      - WHISPER_MODEL=whisper-1 # <- not needed if using ASR

      - ASR_BASE_URL=http://192.168.x.x:9000 #<--- this is the IP of the above ASR container
      - ASR_ENCODE=true
      - ASR_TASK=transcribe
      - ASR_DIARIZE=true
      - ASR_MIN_SPEAKERS=1
      - ASR_MAX_SPEAKERS=5

      - ALLOW_REGISTRATION=false
      - SUMMARY_MAX_TOKENS=8000
      - CHAT_MAX_TOKENS=5000
      - ADMIN_USERNAME=xxx
      - ADMIN_EMAIL=xxx@xxx.ccc
      - ADMIN_PASSWORD=xxx
      - SQLALCHEMY_DATABASE_URI=sqlite:////data/instance/transcriptions.db
      - UPLOAD_FOLDER=/data/uploads
    volumes:
      - /speakr/uploads:/data/uploads      
      - /speakr/instance:/data/instance
```
