### ISSUE TITLE
I want to use openai. How do I configure the URL? I got an error.

### ISSUE THREAD

**Issue by aiastia** [murtaza-nasir/speakr#5]
```
speakr  | [2025-05-09 05:38:31,717] ERROR in app: Processing FAILED for recording 1: Error code: 404 - {'error': {'code': '', 'message': 'Invalid URL (POST /api/v1/audio/transcriptions)', 'type': 'invalid_request_error'}}
speakr  | Traceback (most recent call last):
speakr  |   File "/app/app.py", line 246, in transcribe_audio_task
speakr  |     transcript = transcription_client.audio.transcriptions.create(
speakr  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
speakr  |   File "/usr/local/lib/python3.11/site-packages/openai/resources/audio/transcriptions.py", line 99, in create
speakr  |     return self._post(
speakr  |            ^^^^^^^^^^^
speakr  |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1055, in post
speakr  |     return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
speakr  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
speakr  |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 834, in request
speakr  |     return self._request(
speakr  |            ^^^^^^^^^^^^^^
speakr  |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 877, in _request
speakr  |     raise self._make_status_error_from_response(err.response) from None
speakr  | openai.NotFoundError: Error code: 404 - {'error': {'code': '', 'message': 'Invalid URL (POST /api/v1/audio/transcriptions)', 'type': 'invalid_request_error'}}
```
```
ERROR in app: Processing FAILED for recording 1: 'str' object has no attribute 'text'
speakr  | Traceback (most recent call last):
speakr  |   File "/app/app.py", line 251, in transcribe_audio_task
speakr  |     recording.transcription = transcript.text
speakr  |                               ^^^^^^^^^^^^^^^
speakr  | AttributeError: 'str' object has no attribute 'text'
```
```
 services:
  app:
    image: learnedmachine/speakr:latest
    container_name: speakr
    restart: unless-stopped
    ports:
      - "8899:8899"
    volumes:
      - ./uploads:/data/uploads
      - ./instance:/data/instance
    environment:
      # Database and upload folder configuration
      - SQLALCHEMY_DATABASE_URI=sqlite:////data/instance/transcriptions.db
      - UPLOAD_FOLDER=/data/uploads
      
      # Text model configuration
      - TEXT_MODEL_BASE_URL=https://***.***.xyz/api/v1
      - TEXT_MODEL_API_KEY=sk-***
      - TEXT_MODEL_NAME=***
      
      # Whisper model configuration
      - TRANSCRIPTION_BASE_URL=https://***.**.xyz
      - TRANSCRIPTION_API_KEY=sk-***
      - WHISPER_MODEL=whisper-1
      
      # Application settings
      - ALLOW_REGISTRATION=true
```
